//get data

export const GETDATA_REQUEST="GETDATA_REQUEST"
export const GETDATA_REQUEST_SUCESS="GETDATA_REQUEST_SUCESS"
export const GETDATA_REQUEST_FAIL="GETDATA_REQUEST_FAIL"


export const EMPTY_DATA="EMPTY_DATA"